# Generated by Django 2.1.1 on 2018-10-03 04:58

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20181002_1617'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='salesmodel',
            managers=[
                ('manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
